name: FISCO-BCOS release Actions
on:
  push:
    tags-ignore:
      - v1.*
    branches-ignore:
      - "**"
  release:
    types: [published, created]

jobs:
  compile_macOS_release:
    name: upload standard binary of macOS
    runs-on: macos-latest
    # if: startsWith(github.ref,'v2')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install rust language
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            /home/runner/.hunter
            /Users/runner/.hunter/
            deps/src
            ccache
          key: hunter-clang-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            hunter-clang-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            hunter-clang-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-
            hunter-clang-v1-notest-${{ runner.temp }}-
      - name: install macOS dependencies
        run: brew install ccache libomp
      - name: configure
        run: export SDKROOT=$(xcrun --sdk macosx --show-sdk-path) && CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake . -DCMAKE_BUILD_TYPE=Release -DTEST=ON -DBUILD_STATIC=ON -DHUNTER_CONFIGURATION_TYPES=Release
      - name: compile
        run: make -j2 && make tar
      - name: tar BcosProBuilder
        run: mv tools/BcosProBuilder . && tar -cvzf BcosProBuilder.tgz BcosProBuilder
      - name: tar fisco-bcos for macOS
        run:  mv fisco-bcos-air/ bin/ && cp tools/BcosAirBuilder/build_chain.sh bin/ && cd bin && strip fisco-bcos && tar -cvzf fisco-bcos.tar.gz fisco-bcos build_chain.sh
      - name: Upload fisco-bcos binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/fisco-bcos.tar.gz
          asset_name: fisco-bcos-macOS-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosNodeService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-pro/BcosNodeService.tgz
          asset_name: BcosNodeService-macOS-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosRpcService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-pro/BcosRpcService.tgz
          asset_name: BcosRpcService-macOS-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosGatewayService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-pro/BcosGatewayService.tgz
          asset_name: BcosGatewayService-macOS-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload build_chain.sh
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tools/BcosAirBuilder/build_chain.sh
          asset_name: build_chain.sh
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosProBuilder
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: BcosProBuilder.tgz
          asset_name: BcosProBuilder.tgz
          tag: ${{ github.ref }}
          overwrite: true
      
  compile_centos_release:
    name: upload standard binary of linux
    runs-on: ubuntu-latest
    container:
      image: docker.io/centos:7
      volumes:
        - /github/home/.hunter:/github/home/.hunter
        - /__w/FISCO-BCOS:/__w/FISCO-BCOS
    steps:
      - name: install CentOS dependencies
        run: |
          yum install -y epel-release centos-release-scl
          yum install -y git make gcc gcc-c++ glibc-static glibc-devel cmake3 ccache llvm-toolset-7 devtoolset-7 libzstd-devel zlib-devel flex bison python-devel python3-devel
          source /opt/rh/devtoolset-7/enable
          alias cmake='cmake3'
          yum install -y https://repo.ius.io/ius-release-el7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          yum swap -y git git224-core
          git --version
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install rust language
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            /home/runner/.hunter
            /github/home/.hunter
            deps/src
            ccache
          key: hunter-centos-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            hunter-centos-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            hunter-centos-v1-notest-${{ runner.temp }}-${{ github.base_ref }}-
            hunter-centos-v1-notest-${{ runner.temp }}-
      - name: configure and compile
        run: |
          source /opt/rh/devtoolset-7/enable
          export LIBCLANG_PATH=/opt/rh/llvm-toolset-7/root/lib64/
          source /opt/rh/llvm-toolset-7/enable
          cmake3 . -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=ON -DTEST=OFF -DHUNTER_CONFIGURATION_TYPES=Release
          make -j4
          make tar
      - name: tar BcosProBuilder
        run: mv tools/BcosProBuilder . && tar -cvzf BcosProBuilder.tgz BcosProBuilder
      - name: tar fisco-bcos for CentOS
        run:  mkdir bin && mv fisco-bcos-air/fisco-bcos bin && cd bin && strip fisco-bcos && tar -cvzf fisco-bcos.tar.gz fisco-bcos
      - name: Upload fisco-bcos binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/fisco-bcos.tar.gz
          asset_name: fisco-bcos-linux-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosNodeService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-pro/BcosNodeService.tgz
          asset_name: BcosNodeService-linux-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosRpcService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-pro/BcosRpcService.tgz
          asset_name: BcosRpcService-linux-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosGatewayService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-pro/BcosGatewayService.tgz
          asset_name: BcosGatewayService-linux-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload build_chain.sh
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tools/BcosAirBuilder/build_chain.sh
          asset_name: build_chain.sh
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosProBuilder
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: BcosProBuilder.tgz
          asset_name: BcosProBuilder.tgz
          tag: ${{ github.ref }}
          overwrite: true