name: FISCO-BCOS release Actions
on:
  push:
    tags-ignore:
      - v1.*
    branches-ignore:
      - "**"
  release:
    types: [published, created]

jobs:
  compile_macOS_release:
    name: upload standard binary of macOS
    runs-on: macos-12
    # if: startsWith(github.ref,'v2')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install rust language
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: install macOS dependencies
        run: brew install ccache libomp gmp
      - name: configure
        run: export SDKROOT=$(xcrun --sdk macosx --show-sdk-path) && CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=ON
      - name: compile
        run: make -j2 && make tar
      - name: tar BcosBuilder
        run: mv tools/BcosBuilder . && tar -cvzf BcosBuilder.tgz BcosBuilder
      - name: tar fisco-bcos for macOS
        run:  mv fisco-bcos-air/ bin/ && cp tools/BcosAirBuilder/build_chain.sh bin/ && cd bin && strip fisco-bcos && tar -cvzf fisco-bcos.tar.gz fisco-bcos build_chain.sh
      - name: Upload fisco-bcos binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/fisco-bcos.tar.gz
          asset_name: fisco-bcos-macOS-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosNodeService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosNodeService.tgz
          asset_name: BcosNodeService-macOS-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosRpcService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosRpcService.tgz
          asset_name: BcosRpcService-macOS-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosGatewayService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosGatewayService.tgz
          asset_name: BcosGatewayService-macOS-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosMaxNodeService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosMaxNodeService.tgz
          asset_name: BcosMaxNodeService-macOS-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosExecutorService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosExecutorService.tgz
          asset_name: BcosExecutorService-macOS-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload build_chain.sh
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tools/BcosAirBuilder/build_chain.sh
          asset_name: build_chain.sh
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosBuilder
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: BcosBuilder.tgz
          asset_name: BcosBuilder.tgz
          tag: ${{ github.ref }}
          overwrite: true
      
  compile_centos_release:
    name: upload standard binary of linux
    runs-on: ubuntu-latest
    container:
      image: docker.io/centos:7
      volumes:
        - /github/home/.hunter:/github/home/.hunter
        - /__w/FISCO-BCOS:/__w/FISCO-BCOS
    steps:
      - name: install CentOS dependencies
        run: |
          yum install -y epel-release centos-release-scl
          yum install -y git make gcc gcc-c++ glibc-static glibc-devel gmp-static cmake3 patch ccache llvm-toolset-7 devtoolset-11 libzstd-devel zlib-devel flex bison python-devel python3-devel wget devtoolset-11 rh-perl530-perl
          source /opt/rh/devtoolset-11/enable
          alias cmake='cmake3'
          yum install -y http://opensource.wandisco.com/centos/7/git/x86_64/wandisco-git-release-7-2.noarch.rpm
          yum install -y git
          git --version
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install rust language
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: configure and compile
        run: |
          source /opt/rh/devtoolset-11/enable
          source /opt/rh/rh-perl530/enable
          export LIBCLANG_PATH=/opt/rh/llvm-toolset-7/root/lib64/
          source /opt/rh/llvm-toolset-7/enable
          cmake3 . -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=ON -DTEST=OFF
          make -j4
          make tar
      - name: tar fisco-bcos for CentOS
        run:  mkdir bin && mv fisco-bcos-air/fisco-bcos bin && cd bin && strip fisco-bcos && tar -cvzf fisco-bcos.tar.gz fisco-bcos
      - name: Upload fisco-bcos binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/fisco-bcos.tar.gz
          asset_name: fisco-bcos-linux-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosNodeService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosNodeService.tgz
          asset_name: BcosNodeService-linux-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosRpcService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosRpcService.tgz
          asset_name: BcosRpcService-linux-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosGatewayService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosGatewayService.tgz
          asset_name: BcosGatewayService-linux-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosMaxNodeService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosMaxNodeService.tgz
          asset_name: BcosMaxNodeService-linux-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload BcosExecutorService binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fisco-bcos-tars-service/BcosExecutorService.tgz
          asset_name: BcosExecutorService-linux-x86_64.tgz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload build_chain.sh
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tools/BcosAirBuilder/build_chain.sh
          asset_name: build_chain.sh
          tag: ${{ github.ref }}
          overwrite: true